#!/usr/bin/env bash
#bash script
PIDFILE="/var/run/myscript.pid"
echo $$ > "$PIDFILE" 2>/dev/null || exit 1
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid ; exit' EXIT
trap 'exit' SIGQUIT
while true
do 
   echo 'To infinity and beyond'
done
